step3:step3.o
	gcc -o step3 step3.o
step3.o:step3.c
	gcc  -std=gnu99 -Werror -Wall -pedantic -c step3.c 
step2:step2.o
	gcc -o step2 step2.o
step2.o:step2.c
	gcc -std=gnu99 -Werror -Wall -pedantic -c step2.c
step1:step1.o
	gcc -o step1 step1.o
step1.o:step1.c
	gcc -std=gnu99 -Wall -Werror -pedantic -c step1.c
